import type { Metadata } from "next";
import React from "react";

// export const metadata: Metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function DashboardLayout({
  profile,
  newreleases,
  toptracks,
  topartists,
  recommendedartists,
  recommendedtracks,
}: {
  profile: React.ReactNode;
  newreleases: React.ReactNode;
  toptracks: React.ReactNode;
  topartists: React.ReactNode;
  recommendedartists: React.ReactNode;
  recommendedtracks: React.ReactNode;
}) {
 
  return (
    <>
      <div 
        className="h-full flex flex-wrap flex-row w-full"
      >
          {profile}
          {newreleases}
          {toptracks}
          {topartists}
          {recommendedtracks}
          {/* {recommendedartists} */}
      </div>
    </>
  );
}